/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author hoarlos
 */
public class CRUDEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form CRUDEmpleado
     */
    public CRUDEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMUsuarios = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpOpcionesEmp = new javax.swing.JPanel();
        btnNuevoEmp = new javax.swing.JButton();
        btnRegistrarEmp = new javax.swing.JButton();
        btnBuscarEmp = new javax.swing.JButton();
        btnActualizarEmp = new javax.swing.JButton();
        btnEliminarEmp = new javax.swing.JButton();
        jpCardEmp = new javax.swing.JPanel();
        jpConsultaEmp = new javax.swing.JPanel();
        jSPEmp = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        btnExtraerEmp = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnListarEmp = new javax.swing.JButton();
        txtFiltroNombreEmp = new javax.swing.JTextField();
        jpDatosEmp = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtUsuarioEmp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDniEmp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtContraEmp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cboCargoEmp = new javax.swing.JComboBox<>();
        cboGeneroEmp = new javax.swing.JComboBox<>();
        cboEstadoEmp = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jpModificarEmp = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txtNombresEmpM = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtUsuarioEmpM = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtDniEmpM = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtContraEmpM = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cboCargoEmpM = new javax.swing.JComboBox<>();
        cboGeneroEmpM = new javax.swing.JComboBox<>();
        cboEstadoEmpM = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtCodigoEmpM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpMUsuarios.setBackground(new java.awt.Color(0, 51, 51));
        jpMUsuarios.setPreferredSize(new java.awt.Dimension(400, 150));
        jpMUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario125x125.png"))); // NOI18N
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel25.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel25.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpMUsuarios.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 130, 130));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MANTENIMIENTO DE EMPLEADOS");
        jpMUsuarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 15, 970, 30));

        jpOpcionesEmp.setBackground(new java.awt.Color(0, 51, 51));

        btnNuevoEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevoEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new32x32.png"))); // NOI18N
        btnNuevoEmp.setText("NUEVO");
        btnNuevoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnNuevoEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });
        jpOpcionesEmp.add(btnNuevoEmp);

        btnRegistrarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save32x32.png"))); // NOI18N
        btnRegistrarEmp.setText("REGISTRAR");
        btnRegistrarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEmp.setEnabled(false);
        btnRegistrarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnRegistrarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnRegistrarEmp);

        btnBuscarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search32x32.png"))); // NOI18N
        btnBuscarEmp.setText("CONSULTAR");
        btnBuscarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnBuscarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpActionPerformed(evt);
            }
        });
        jpOpcionesEmp.add(btnBuscarEmp);

        btnActualizarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update32x32.png"))); // NOI18N
        btnActualizarEmp.setText("ACTUALIZAR");
        btnActualizarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarEmp.setEnabled(false);
        btnActualizarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnActualizarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnActualizarEmp);

        btnEliminarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete32x32.png"))); // NOI18N
        btnEliminarEmp.setText("ELIMINAR");
        btnEliminarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnEliminarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnEliminarEmp);

        jpMUsuarios.add(jpOpcionesEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 50, 970, 85));

        jpCardEmp.setLayout(new java.awt.CardLayout());

        jpConsultaEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpConsultaEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSPEmp.setBackground(new java.awt.Color(255, 255, 255));
        jSPEmp.setOpaque(false);

        tblEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRES Y APELLIDOS", "CARGO", "DNI", "GÉNERO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleado.setOpaque(false);
        tblEmpleado.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tblEmpleado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEmpleado.getTableHeader().setResizingAllowed(false);
        tblEmpleado.getTableHeader().setReorderingAllowed(false);
        jSPEmp.setViewportView(tblEmpleado);

        jpConsultaEmp.add(jSPEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 930, 280));

        btnExtraerEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnExtraerEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExtraerEmp.setText("MODIFICAR USUARIO");
        jpConsultaEmp.add(btnExtraerEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 220, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("FILTRAR POR NOMBRE O APELLIDO:");
        jpConsultaEmp.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 30));

        btnListarEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnListarEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListarEmp.setText("LISTAR");
        jpConsultaEmp.add(btnListarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 15, 120, 40));

        txtFiltroNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jpConsultaEmp.add(txtFiltroNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 30));

        jpCardEmp.add(jpConsultaEmp, "card3");

        jpDatosEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpDatosEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NOMBRES Y APELLIDOS:");
        jpDatosEmp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        txtNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombreEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 300, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("CARGO:");
        jpDatosEmp.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("USUARIO:");
        jpDatosEmp.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 30));

        txtUsuarioEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUsuarioEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsuarioEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtUsuarioEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 220, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("D.N.I.:");
        jpDatosEmp.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        txtDniEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtDniEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("CONTRASEÑA:");
        jpDatosEmp.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, 30));

        txtContraEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtContraEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtContraEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 220, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("GÉNERO:");
        jpDatosEmp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 30));

        cboCargoEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboCargoEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Cajero" }));
        cboCargoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboCargoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboCargoEmp.setEditor(null);
        jpDatosEmp.add(cboCargoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 30));

        cboGeneroEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroEmp.setEditor(null);
        jpDatosEmp.add(cboGeneroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 220, 30));

        cboEstadoEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboEstadoEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Inactivo" }));
        cboEstadoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboEstadoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboEstadoEmp.setEditor(null);
        jpDatosEmp.add(cboEstadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("ESTADO:");
        jpDatosEmp.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 30));

        jpCardEmp.add(jpDatosEmp, "card2");

        jpModificarEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpModificarEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("NOMBRES Y APELLIDOS:");
        jpModificarEmp.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        txtNombresEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombresEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombresEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombresEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtNombresEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("CARGO:");
        jpModificarEmp.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("USUARIO:");
        jpModificarEmp.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 30));

        txtUsuarioEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUsuarioEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsuarioEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtUsuarioEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 220, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("D.N.I.:");
        jpModificarEmp.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        txtDniEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtDniEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("CONTRASEÑA:");
        jpModificarEmp.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 30));

        txtContraEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtContraEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtContraEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 220, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("GÉNERO:");
        jpModificarEmp.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 30));

        cboCargoEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboCargoEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Cajero" }));
        cboCargoEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboCargoEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboCargoEmpM.setEditor(null);
        jpModificarEmp.add(cboCargoEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        cboGeneroEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroEmpM.setEditor(null);
        jpModificarEmp.add(cboGeneroEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 220, 30));

        cboEstadoEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboEstadoEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Inactivo" }));
        cboEstadoEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboEstadoEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboEstadoEmpM.setEditor(null);
        jpModificarEmp.add(cboEstadoEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("ESTADO:");
        jpModificarEmp.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("CÓDIGO:");
        jpModificarEmp.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        txtCodigoEmpM.setEditable(false);
        txtCodigoEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCodigoEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtCodigoEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, 30));

        jpCardEmp.add(jpModificarEmp, "card4");

        jpMUsuarios.add(jpCardEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 140, 970, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed

    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void btnBuscarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpActionPerformed

    }//GEN-LAST:event_btnBuscarEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnActualizarEmp;
    public static javax.swing.JButton btnBuscarEmp;
    public static javax.swing.JButton btnEliminarEmp;
    public static javax.swing.JButton btnExtraerEmp;
    public static javax.swing.JButton btnListarEmp;
    public static javax.swing.JButton btnNuevoEmp;
    public static javax.swing.JButton btnRegistrarEmp;
    public static javax.swing.JComboBox<String> cboCargoEmp;
    public static javax.swing.JComboBox<String> cboCargoEmpM;
    public static javax.swing.JComboBox<String> cboEstadoEmp;
    public static javax.swing.JComboBox<String> cboEstadoEmpM;
    public static javax.swing.JComboBox<String> cboGeneroEmp;
    public static javax.swing.JComboBox<String> cboGeneroEmpM;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    public static javax.swing.JScrollPane jSPEmp;
    public static javax.swing.JPanel jpCardEmp;
    public static javax.swing.JPanel jpConsultaEmp;
    public static javax.swing.JPanel jpDatosEmp;
    public static javax.swing.JPanel jpMUsuarios;
    public static javax.swing.JPanel jpModificarEmp;
    public static javax.swing.JPanel jpOpcionesEmp;
    public static javax.swing.JTable tblEmpleado;
    public static javax.swing.JTextField txtCodigoEmpM;
    public static javax.swing.JTextField txtContraEmp;
    public static javax.swing.JTextField txtContraEmpM;
    public static javax.swing.JTextField txtDniEmp;
    public static javax.swing.JTextField txtDniEmpM;
    public static javax.swing.JTextField txtFiltroNombreEmp;
    public static javax.swing.JTextField txtNombreEmp;
    public static javax.swing.JTextField txtNombresEmpM;
    public static javax.swing.JTextField txtUsuarioEmp;
    public static javax.swing.JTextField txtUsuarioEmpM;
    // End of variables declaration//GEN-END:variables
}
