/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author hoarlos
 */
public class JFCliente extends javax.swing.JFrame {

    public JFCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpOpcionesEmp = new javax.swing.JPanel();
        btnNuevoEmp = new javax.swing.JButton();
        btnRegistrarEmp = new javax.swing.JButton();
        btnBuscarEmp = new javax.swing.JButton();
        btnActualizarEmp = new javax.swing.JButton();
        btnEliminarEmp = new javax.swing.JButton();
        jpCardEmp = new javax.swing.JPanel();
        jpDatosEmp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDniEmp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContraEmp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboCargoEmp = new javax.swing.JComboBox<>();
        cboGeneroEmp = new javax.swing.JComboBox<>();
        cboEstadoEmp = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jpConsultaEmp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        btnExtraerEmp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnListarEmp = new javax.swing.JButton();
        txtFiltroNombreEmp = new javax.swing.JTextField();
        jpModificarEmp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombresEmpM = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUsuarioEmpM = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDniEmpM = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtContraEmpM = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cboCargoEmpM = new javax.swing.JComboBox<>();
        cboGeneroEmpM = new javax.swing.JComboBox<>();
        cboEstadoEmpM = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtCodigoM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        jpEmpleados.setBackground(new java.awt.Color(51, 51, 51));
        jpEmpleados.setMaximumSize(new java.awt.Dimension(1000, 600));
        jpEmpleados.setMinimumSize(new java.awt.Dimension(1000, 600));
        jpEmpleados.setPreferredSize(new java.awt.Dimension(1000, 600));
        jpEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANTENIMIENTO DE USUARIOS");
        jpEmpleados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 970, 30));

        jpOpcionesEmp.setBackground(new java.awt.Color(51, 51, 51));

        btnNuevoEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevoEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new32x32.png"))); // NOI18N
        btnNuevoEmp.setText("NUEVO");
        btnNuevoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnNuevoEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });
        jpOpcionesEmp.add(btnNuevoEmp);

        btnRegistrarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save32x32.png"))); // NOI18N
        btnRegistrarEmp.setText("REGISTRAR");
        btnRegistrarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnRegistrarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnRegistrarEmp);

        btnBuscarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search32x32.png"))); // NOI18N
        btnBuscarEmp.setText("BUSCAR");
        btnBuscarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnBuscarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpActionPerformed(evt);
            }
        });
        jpOpcionesEmp.add(btnBuscarEmp);

        btnActualizarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update32x32.png"))); // NOI18N
        btnActualizarEmp.setText("ACTUALIZAR");
        btnActualizarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnActualizarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnActualizarEmp);

        btnEliminarEmp.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete32x32.png"))); // NOI18N
        btnEliminarEmp.setText("ELIMINAR");
        btnEliminarEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarEmp.setPreferredSize(new java.awt.Dimension(120, 75));
        btnEliminarEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesEmp.add(btnEliminarEmp);

        jpEmpleados.add(jpOpcionesEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 970, 85));

        jpCardEmp.setLayout(new java.awt.CardLayout());

        jpDatosEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpDatosEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOMBRES:");
        jpDatosEmp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        txtNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombreEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 300, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CARGO:");
        jpDatosEmp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("USUARIO:");
        jpDatosEmp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        txtUsuarioEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUsuarioEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsuarioEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtUsuarioEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("D.N.I.:");
        jpDatosEmp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        txtDniEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtDniEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CONTRASEÑA:");
        jpDatosEmp.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        txtContraEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtContraEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosEmp.add(txtContraEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("GÉNERO:");
        jpDatosEmp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 30));

        cboCargoEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboCargoEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Cajero" }));
        cboCargoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboCargoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboCargoEmp.setEditor(null);
        jpDatosEmp.add(cboCargoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 30));

        cboGeneroEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroEmp.setEditor(null);
        jpDatosEmp.add(cboGeneroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 220, 30));

        cboEstadoEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboEstadoEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Inactivo" }));
        cboEstadoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboEstadoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboEstadoEmp.setEditor(null);
        jpDatosEmp.add(cboEstadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("ESTADO:");
        jpDatosEmp.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 30));

        jpCardEmp.add(jpDatosEmp, "card2");

        jpConsultaEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpConsultaEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tblEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRES Y APELLIDOS", "DNI", "RUC", "GÉNERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleado.setOpaque(false);
        tblEmpleado.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblEmpleado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEmpleado.getTableHeader().setResizingAllowed(false);
        tblEmpleado.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmpleado);

        jpConsultaEmp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 930, 330));

        btnExtraerEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnExtraerEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExtraerEmp.setText("MODIFICAR CLIENTE");
        jpConsultaEmp.add(btnExtraerEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FILTRAR POR NOMBRE O APELLIDO:");
        jpConsultaEmp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 30));

        btnListarEmp.setBackground(new java.awt.Color(51, 51, 51));
        btnListarEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListarEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnListarEmp.setText("LISTAR");
        jpConsultaEmp.add(btnListarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 15, 120, 40));

        txtFiltroNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jpConsultaEmp.add(txtFiltroNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 30));

        jpCardEmp.add(jpConsultaEmp, "card3");

        jpModificarEmp.setBackground(new java.awt.Color(255, 255, 255));
        jpModificarEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("NOMBRES:");
        jpModificarEmp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        txtNombresEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombresEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombresEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombresEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtNombresEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("CARGO:");
        jpModificarEmp.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("USUARIO:");
        jpModificarEmp.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        txtUsuarioEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUsuarioEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsuarioEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtUsuarioEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("D.N.I.:");
        jpModificarEmp.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        txtDniEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtDniEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("CONTRASEÑA:");
        jpModificarEmp.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 30));

        txtContraEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtContraEmpM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtContraEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 220, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("GÉNERO:");
        jpModificarEmp.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 30));

        cboCargoEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboCargoEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Cajero" }));
        cboCargoEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboCargoEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboCargoEmpM.setEditor(null);
        jpModificarEmp.add(cboCargoEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        cboGeneroEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroEmpM.setEditor(null);
        jpModificarEmp.add(cboGeneroEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 220, 30));

        cboEstadoEmpM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboEstadoEmpM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Inactivo" }));
        cboEstadoEmpM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboEstadoEmpM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboEstadoEmpM.setEditor(null);
        jpModificarEmp.add(cboEstadoEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("ESTADO:");
        jpModificarEmp.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("CÓDIGO:");
        jpModificarEmp.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 30));

        txtCodigoM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCodigoM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificarEmp.add(txtCodigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 220, 30));

        jpCardEmp.add(jpModificarEmp, "card4");

        jpEmpleados.add(jpCardEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 970, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed
        
    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void btnBuscarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpActionPerformed
        
    }//GEN-LAST:event_btnBuscarEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnActualizarEmp;
    public static javax.swing.JButton btnBuscarEmp;
    public static javax.swing.JButton btnEliminarEmp;
    public static javax.swing.JButton btnExtraerEmp;
    public static javax.swing.JButton btnListarEmp;
    public static javax.swing.JButton btnNuevoEmp;
    public static javax.swing.JButton btnRegistrarEmp;
    public static javax.swing.JComboBox<String> cboCargoEmp;
    public static javax.swing.JComboBox<String> cboCargoEmpM;
    public static javax.swing.JComboBox<String> cboEstadoEmp;
    public static javax.swing.JComboBox<String> cboEstadoEmpM;
    public static javax.swing.JComboBox<String> cboGeneroEmp;
    public static javax.swing.JComboBox<String> cboGeneroEmpM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel jpCardEmp;
    public static javax.swing.JPanel jpConsultaEmp;
    public static javax.swing.JPanel jpDatosEmp;
    private javax.swing.JPanel jpEmpleados;
    public static javax.swing.JPanel jpModificarEmp;
    private javax.swing.JPanel jpOpcionesEmp;
    public static javax.swing.JTable tblEmpleado;
    public static javax.swing.JTextField txtCodigoM;
    public static javax.swing.JTextField txtContraEmp;
    public static javax.swing.JTextField txtContraEmpM;
    public static javax.swing.JTextField txtDniEmp;
    public static javax.swing.JTextField txtDniEmpM;
    public static javax.swing.JTextField txtFiltroNombreEmp;
    public static javax.swing.JTextField txtNombreEmp;
    public static javax.swing.JTextField txtNombresEmpM;
    public static javax.swing.JTextField txtUsuarioEmp;
    public static javax.swing.JTextField txtUsuarioEmpM;
    // End of variables declaration//GEN-END:variables

    
}
