/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Administrador
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVenta
     */
    public JFMenuPrincipal() {
        initComponents();
        this.setTitle("SISTEMA DE VENTAS");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jpCarrusel = new javax.swing.JPanel();
        jpVenta = new javax.swing.JPanel();
        jpCompra = new javax.swing.JPanel();
        jpReportes = new javax.swing.JPanel();
        jpMantenimiento1 = new javax.swing.JPanel();
        jpClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCantClientes = new javax.swing.JLabel();
        btnEntrarClientes = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblCantProductos = new javax.swing.JLabel();
        btnEntrarProductos = new javax.swing.JButton();
        jpUsuarios = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblCantUsuarios = new javax.swing.JLabel();
        btnEntrarUsuario = new javax.swing.JButton();
        jpProveedores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCantProveedores = new javax.swing.JLabel();
        btnEntrarProveedor = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jpConfiguracion = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        lblNombNegocio = new javax.swing.JLabel();
        lblIcoUser = new javax.swing.JLabel();
        lblNombUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnItemCerrarSesion = new javax.swing.JMenuItem();
        mnItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 680));
        setPreferredSize(new java.awt.Dimension(1300, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta32x32.png"))); // NOI18N
        jButton1.setText("REALIZAR VENTA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHideActionText(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(20, 10, 10, 10));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 150, 70));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/configuracion32x32.png"))); // NOI18N
        jButton2.setText("CONFIGURACIÓN");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHideActionText(true);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(20, 10, 10, 10));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jpMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 150, 70));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra32x32.png"))); // NOI18N
        jButton3.setText("GUARDAR COMPRAS");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHideActionText(true);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(20, 10, 10, 10));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jpMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 90, 150, 70));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte32x32.png"))); // NOI18N
        jButton4.setText("REPORTES");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHideActionText(true);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(20, 10, 10, 10));
        jButton4.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jpMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 150, 70));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mantenimiento32x32.png"))); // NOI18N
        jButton5.setText("MANTENIMIENTO");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHideActionText(true);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMargin(new java.awt.Insets(20, 10, 10, 10));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jpMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 150, 70));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 600));

        jpCarrusel.setLayout(new java.awt.CardLayout());
        jpCarrusel.add(jpVenta, "card2");
        jpCarrusel.add(jpCompra, "card3");
        jpCarrusel.add(jpReportes, "card4");

        jpMantenimiento1.setBackground(new java.awt.Color(255, 255, 255));
        jpMantenimiento1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpClientes.setBackground(new java.awt.Color(0, 204, 153));
        jpClientes.setPreferredSize(new java.awt.Dimension(400, 150));
        jpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente125x125.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENTES");
        jpClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantClientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantClientes.setText("22");
        jpClientes.add(lblCantClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarClientes.setText("ENTRAR");
        btnEntrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarClientesActionPerformed(evt);
            }
        });
        jpClientes.add(btnEntrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento1.add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jpProductos.setBackground(new java.awt.Color(255, 204, 0));
        jpProductos.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/productos125x125.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel22.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel22.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProductos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("PRODUCTOS");
        jpProductos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProductos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProductos.setText("60");
        jpProductos.add(lblCantProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProductos.setText("ENTRAR");
        btnEntrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProductosActionPerformed(evt);
            }
        });
        jpProductos.add(btnEntrarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento1.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jpUsuarios.setBackground(new java.awt.Color(255, 255, 102));
        jpUsuarios.setPreferredSize(new java.awt.Dimension(400, 150));
        jpUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario125x125.png"))); // NOI18N
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel25.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel25.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpUsuarios.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("USUARIOS");
        jpUsuarios.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantUsuarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantUsuarios.setText("2");
        jpUsuarios.add(lblCantUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarUsuario.setText("ENTRAR");
        btnEntrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarUsuarioActionPerformed(evt);
            }
        });
        jpUsuarios.add(btnEntrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento1.add(jpUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jpProveedores.setBackground(new java.awt.Color(0, 204, 255));
        jpProveedores.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedor125x125.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel5.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROVEEDORES");
        jpProveedores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProveedores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProveedores.setText("14");
        jpProveedores.add(lblCantProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProveedor.setText("ENTRAR");
        btnEntrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProveedorActionPerformed(evt);
            }
        });
        jpProveedores.add(btnEntrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento1.add(jpProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MANTENIMIENTO");
        jpMantenimiento1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 840, 30));

        jpCarrusel.add(jpMantenimiento1, "card2");
        jpCarrusel.add(jpConfiguracion, "card6");

        getContentPane().add(jpCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 1140, 600));

        jpTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombNegocio.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNombNegocio.setForeground(new java.awt.Color(255, 255, 255));
        lblNombNegocio.setText("BODEGA MADYSON");
        jpTitulo.add(lblNombNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 40));

        lblIcoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/admin32x32.png"))); // NOI18N
        jpTitulo.add(lblIcoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 40, 40));

        lblNombUser.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNombUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNombUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombUser.setText("ADMINISTRADOR");
        lblNombUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jpTitulo.add(lblNombUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 200, 40));

        getContentPane().add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 20));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("SISTEMA");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 21));

        mnItemCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        mnItemCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnItemCerrarSesion.setText("CERRAR SESIÓN");
        jMenu1.add(mnItemCerrarSesion);

        mnItemSalir.setBackground(new java.awt.Color(255, 255, 255));
        mnItemSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnItemSalir.setText("SALIR");
        mnItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnItemSalirActionPerformed

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void btnEntrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarClientesActionPerformed
        crudClientes();
    }//GEN-LAST:event_btnEntrarClientesActionPerformed

    private void btnEntrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProductosActionPerformed
        crudProductos();
    }//GEN-LAST:event_btnEntrarProductosActionPerformed

    private void btnEntrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarUsuarioActionPerformed
        crudUsuarios();
    }//GEN-LAST:event_btnEntrarUsuarioActionPerformed

    private void btnEntrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProveedorActionPerformed
        crudProveedor();
    }//GEN-LAST:event_btnEntrarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarClientes;
    private javax.swing.JButton btnEntrarProductos;
    private javax.swing.JButton btnEntrarProveedor;
    private javax.swing.JButton btnEntrarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpCarrusel;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JPanel jpConfiguracion;
    private javax.swing.JPanel jpMantenimiento1;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedores;
    private javax.swing.JPanel jpReportes;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JPanel jpVenta;
    private javax.swing.JLabel lblCantClientes;
    private javax.swing.JLabel lblCantProductos;
    private javax.swing.JLabel lblCantProveedores;
    private javax.swing.JLabel lblCantUsuarios;
    private javax.swing.JLabel lblIcoUser;
    private javax.swing.JLabel lblNombNegocio;
    private javax.swing.JLabel lblNombUser;
    private javax.swing.JMenuItem mnItemCerrarSesion;
    private javax.swing.JMenuItem mnItemSalir;
    // End of variables declaration//GEN-END:variables

    private void crudClientes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void crudUsuarios() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void crudProveedor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void crudProductos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
