/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Administrador
 */
public class JFPrincipal extends javax.swing.JFrame {

    
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBase = new javax.swing.JPanel();
        jpIniciarSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        icoPass = new javax.swing.JLabel();
        icoUser = new javax.swing.JLabel();
        jpSistemaon = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        btnJpVenta = new javax.swing.JButton();
        btnJpConfiguracion = new javax.swing.JButton();
        btnJpCompra = new javax.swing.JButton();
        btnJpReportes = new javax.swing.JButton();
        btnJpMantenimiento = new javax.swing.JButton();
        jpCardMant = new javax.swing.JPanel();
        jpVenta = new javax.swing.JPanel();
        jpCompra = new javax.swing.JPanel();
        jpReportes = new javax.swing.JPanel();
        jpMantenimiento = new javax.swing.JPanel();
        jpClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpOpcionesCli = new javax.swing.JPanel();
        btnNuevoCli = new javax.swing.JButton();
        btnRegistrarCli = new javax.swing.JButton();
        btnBuscarCli = new javax.swing.JButton();
        btnActualizarCli = new javax.swing.JButton();
        btnEliminarCli = new javax.swing.JButton();
        jpCardCli = new javax.swing.JPanel();
        jpDatosCli = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApePatCli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApeMatCli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDniCli = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRucCli = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboGeneroCli = new javax.swing.JComboBox<>();
        jpConsultaCli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnExtraer = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        txtFiltroNombre = new javax.swing.JTextField();
        jpModificar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreCliM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtApePatCliM = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtApeMatCliM = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDniCliM = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRucCliM = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cboGeneroCliM = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtCodigoCliM = new javax.swing.JTextField();
        jpProductos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblCantProductos = new javax.swing.JLabel();
        btnEntrarProductos = new javax.swing.JButton();
        jpUsuarios = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblCantUsuarios = new javax.swing.JLabel();
        btnEntrarUsuario = new javax.swing.JButton();
        jpProveedores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCantProveedores = new javax.swing.JLabel();
        btnEntrarProveedor = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jpConfiguracion = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        lblNombNegocio = new javax.swing.JLabel();
        lblIcoUser = new javax.swing.JLabel();
        lblNombUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSistema = new javax.swing.JMenu();
        mnItemCerrarSesion = new javax.swing.JMenuItem();
        mnItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBase.setLayout(new java.awt.CardLayout());

        jpIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jpIniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIAR SESIÓN");
        jpIniciarSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 279, 26));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/users.png"))); // NOI18N
        jpIniciarSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 250));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("USUARIO:");
        jpIniciarSesion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CONTRASEÑA:");
        jpIniciarSesion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 140, 30));

        txtContrasenia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContrasenia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyTyped(evt);
            }
        });
        jpIniciarSesion.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 200, 30));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpIniciarSesion.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 200, 30));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(51, 51, 51));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jpIniciarSesion.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 200, 40));
        jpIniciarSesion.add(icoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 193, 26, 26));
        jpIniciarSesion.add(icoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 114, 26, 26));

        jpBase.add(jpIniciarSesion, "card2");

        jpSistemaon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(255, 255, 255)));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJpVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnJpVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJpVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta32x32.png"))); // NOI18N
        btnJpVenta.setText("REALIZAR VENTA");
        btnJpVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJpVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJpVenta.setHideActionText(true);
        btnJpVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJpVenta.setMargin(new java.awt.Insets(20, 10, 10, 10));
        btnJpVenta.setPreferredSize(new java.awt.Dimension(150, 80));
        btnJpVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJpVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJpVentaActionPerformed(evt);
            }
        });
        jpMenu.add(btnJpVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 150, 70));

        btnJpConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        btnJpConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJpConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/configuracion32x32.png"))); // NOI18N
        btnJpConfiguracion.setText("CONFIGURACIÓN");
        btnJpConfiguracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJpConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJpConfiguracion.setEnabled(false);
        btnJpConfiguracion.setHideActionText(true);
        btnJpConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJpConfiguracion.setMargin(new java.awt.Insets(20, 10, 10, 10));
        btnJpConfiguracion.setPreferredSize(new java.awt.Dimension(150, 80));
        btnJpConfiguracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpMenu.add(btnJpConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 150, 70));

        btnJpCompra.setBackground(new java.awt.Color(204, 204, 204));
        btnJpCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJpCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra32x32.png"))); // NOI18N
        btnJpCompra.setText("GUARDAR COMPRAS");
        btnJpCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJpCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJpCompra.setEnabled(false);
        btnJpCompra.setHideActionText(true);
        btnJpCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJpCompra.setMargin(new java.awt.Insets(20, 10, 10, 10));
        btnJpCompra.setPreferredSize(new java.awt.Dimension(150, 80));
        btnJpCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpMenu.add(btnJpCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 90, 150, 70));

        btnJpReportes.setBackground(new java.awt.Color(204, 204, 204));
        btnJpReportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJpReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte32x32.png"))); // NOI18N
        btnJpReportes.setText("REPORTES");
        btnJpReportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJpReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJpReportes.setHideActionText(true);
        btnJpReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJpReportes.setMargin(new java.awt.Insets(20, 10, 10, 10));
        btnJpReportes.setPreferredSize(new java.awt.Dimension(150, 80));
        btnJpReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJpReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJpReportesActionPerformed(evt);
            }
        });
        jpMenu.add(btnJpReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 150, 70));

        btnJpMantenimiento.setBackground(new java.awt.Color(204, 204, 204));
        btnJpMantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJpMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mantenimiento32x32.png"))); // NOI18N
        btnJpMantenimiento.setText("MANTENIMIENTO");
        btnJpMantenimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJpMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJpMantenimiento.setHideActionText(true);
        btnJpMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJpMantenimiento.setMargin(new java.awt.Insets(20, 10, 10, 10));
        btnJpMantenimiento.setPreferredSize(new java.awt.Dimension(150, 80));
        btnJpMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJpMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJpMantenimientoActionPerformed(evt);
            }
        });
        jpMenu.add(btnJpMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 150, 70));

        jpSistemaon.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 600));

        jpCardMant.setLayout(new java.awt.CardLayout());
        jpCardMant.add(jpVenta, "card2");
        jpCardMant.add(jpCompra, "card3");
        jpCardMant.add(jpReportes, "card4");

        jpMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        jpMantenimiento.setLayout(new java.awt.CardLayout());

        jpClientes.setBackground(new java.awt.Color(51, 51, 51));
        jpClientes.setPreferredSize(new java.awt.Dimension(400, 150));
        jpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente125x125.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MANTENIMIENTO DE CLIENTES");
        jpClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 15, 970, 30));

        jpOpcionesCli.setBackground(new java.awt.Color(51, 51, 51));

        btnNuevoCli.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevoCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new32x32.png"))); // NOI18N
        btnNuevoCli.setText("NUEVO");
        btnNuevoCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoCli.setPreferredSize(new java.awt.Dimension(120, 75));
        btnNuevoCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCliActionPerformed(evt);
            }
        });
        jpOpcionesCli.add(btnNuevoCli);

        btnRegistrarCli.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save32x32.png"))); // NOI18N
        btnRegistrarCli.setText("REGISTRAR");
        btnRegistrarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarCli.setPreferredSize(new java.awt.Dimension(120, 75));
        btnRegistrarCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesCli.add(btnRegistrarCli);

        btnBuscarCli.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search32x32.png"))); // NOI18N
        btnBuscarCli.setText("BUSCAR");
        btnBuscarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCli.setPreferredSize(new java.awt.Dimension(120, 75));
        btnBuscarCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });
        jpOpcionesCli.add(btnBuscarCli);

        btnActualizarCli.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update32x32.png"))); // NOI18N
        btnActualizarCli.setText("ACTUALIZAR");
        btnActualizarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarCli.setPreferredSize(new java.awt.Dimension(120, 75));
        btnActualizarCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesCli.add(btnActualizarCli);

        btnEliminarCli.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete32x32.png"))); // NOI18N
        btnEliminarCli.setText("ELIMINAR");
        btnEliminarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarCli.setPreferredSize(new java.awt.Dimension(120, 75));
        btnEliminarCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpOpcionesCli.add(btnEliminarCli);

        jpClientes.add(jpOpcionesCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 50, 970, 85));

        jpCardCli.setLayout(new java.awt.CardLayout());

        jpDatosCli.setBackground(new java.awt.Color(255, 255, 255));
        jpDatosCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("NOMBRES:");
        jpDatosCli.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        txtNombreCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombreCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosCli.add(txtNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 450, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("APELLIDO PATERNO:");
        jpDatosCli.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        txtApePatCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtApePatCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApePatCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApePatCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosCli.add(txtApePatCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("APELLIDO MATERNO:");
        jpDatosCli.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 200, 30));

        txtApeMatCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtApeMatCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApeMatCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApeMatCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosCli.add(txtApeMatCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("D.N.I.:");
        jpDatosCli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        txtDniCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosCli.add(txtDniCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("R.U.C.:");
        jpDatosCli.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 200, 30));

        txtRucCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtRucCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRucCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpDatosCli.add(txtRucCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 220, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("GÉNERO:");
        jpDatosCli.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        cboGeneroCli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroCli.setEditor(null);
        jpDatosCli.add(cboGeneroCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        jpCardCli.add(jpDatosCli, "card2");

        jpConsultaCli.setBackground(new java.awt.Color(255, 255, 255));
        jpConsultaCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tblCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRES Y APELLIDOS", "DNI", "RUC", "GÉNERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setOpaque(false);
        tblCliente.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCliente.getTableHeader().setResizingAllowed(false);
        tblCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCliente);

        jpConsultaCli.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 930, 330));

        btnExtraer.setBackground(new java.awt.Color(255, 255, 255));
        btnExtraer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExtraer.setText("MODIFICAR CLIENTE");
        jpConsultaCli.add(btnExtraer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("FILTRAR POR NOMBRE O APELLIDO:");
        jpConsultaCli.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 30));

        btnListar.setBackground(new java.awt.Color(51, 51, 51));
        btnListar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("LISTAR");
        jpConsultaCli.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 15, 120, 40));

        txtFiltroNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jpConsultaCli.add(txtFiltroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 30));

        jpCardCli.add(jpConsultaCli, "card3");

        jpModificar.setBackground(new java.awt.Color(255, 255, 255));
        jpModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("NOMBRES:");
        jpModificar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 200, 30));

        txtNombreCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNombreCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtNombreCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 220, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("APELLIDO PATERNO:");
        jpModificar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        txtApePatCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtApePatCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApePatCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApePatCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtApePatCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("APELLIDO MATERNO:");
        jpModificar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 200, 30));

        txtApeMatCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtApeMatCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApeMatCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApeMatCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtApeMatCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 220, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("D.N.I.:");
        jpModificar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        txtDniCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDniCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtDniCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("R.U.C.:");
        jpModificar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 200, 30));

        txtRucCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtRucCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRucCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtRucCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 220, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("GÉNERO:");
        jpModificar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        cboGeneroCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboGeneroCliM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Hombre", "Mujer" }));
        cboGeneroCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboGeneroCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboGeneroCliM.setEditor(null);
        jpModificar.add(cboGeneroCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("CÓDIGO:");
        jpModificar.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        txtCodigoCliM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCodigoCliM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoCliM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpModificar.add(txtCodigoCliM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, 30));

        jpCardCli.add(jpModificar, "card4");

        jpClientes.add(jpCardCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 140, 970, 450));

        jpMantenimiento.add(jpClientes, "card2");

        jpProductos.setBackground(new java.awt.Color(255, 204, 0));
        jpProductos.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/productos125x125.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel22.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel22.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProductos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("PRODUCTOS");
        jpProductos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProductos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProductos.setText("60");
        jpProductos.add(lblCantProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProductos.setText("ENTRAR");
        btnEntrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProductosActionPerformed(evt);
            }
        });
        jpProductos.add(btnEntrarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpProductos, "card3");

        jpUsuarios.setBackground(new java.awt.Color(255, 255, 102));
        jpUsuarios.setPreferredSize(new java.awt.Dimension(400, 150));
        jpUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario125x125.png"))); // NOI18N
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel25.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel25.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpUsuarios.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("USUARIOS");
        jpUsuarios.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantUsuarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantUsuarios.setText("2");
        jpUsuarios.add(lblCantUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarUsuario.setText("ENTRAR");
        btnEntrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarUsuarioActionPerformed(evt);
            }
        });
        jpUsuarios.add(btnEntrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpUsuarios, "card4");

        jpProveedores.setBackground(new java.awt.Color(0, 204, 255));
        jpProveedores.setPreferredSize(new java.awt.Dimension(400, 150));
        jpProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedor125x125.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel5.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROVEEDORES");
        jpProveedores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        lblCantProveedores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantProveedores.setText("14");
        jpProveedores.add(lblCantProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 80));

        btnEntrarProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrarProveedor.setText("ENTRAR");
        btnEntrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarProveedorActionPerformed(evt);
            }
        });
        jpProveedores.add(btnEntrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 40));

        jpMantenimiento.add(jpProveedores, "card5");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MANTENIMIENTO");
        jpMantenimiento.add(jLabel20, "card6");

        jpCardMant.add(jpMantenimiento, "card2");
        jpCardMant.add(jpConfiguracion, "card6");

        jpSistemaon.add(jpCardMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1140, 600));

        jpBase.add(jpSistemaon, "card3");

        getContentPane().add(jpBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1300, 600));

        jpTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombNegocio.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNombNegocio.setForeground(new java.awt.Color(255, 255, 255));
        lblNombNegocio.setText("BODEGA MADYSON");
        jpTitulo.add(lblNombNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 40));

        lblIcoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/admin32x32.png"))); // NOI18N
        jpTitulo.add(lblIcoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 40, 40));

        lblNombUser.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNombUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNombUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombUser.setText("ADMINISTRADOR");
        lblNombUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jpTitulo.add(lblNombUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 200, 40));

        getContentPane().add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 20));

        mnSistema.setBackground(new java.awt.Color(255, 255, 255));
        mnSistema.setText("SISTEMA");
        mnSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnSistema.setPreferredSize(new java.awt.Dimension(200, 21));

        mnItemCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        mnItemCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnItemCerrarSesion.setText("CERRAR SESIÓN");
        mnItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCerrarSesionActionPerformed(evt);
            }
        });
        mnSistema.add(mnItemCerrarSesion);

        mnItemSalir.setBackground(new java.awt.Color(255, 255, 255));
        mnItemSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnItemSalir.setText("SALIR");
        mnItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSalirActionPerformed(evt);
            }
        });
        mnSistema.add(mnItemSalir);

        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSalirActionPerformed

    }//GEN-LAST:event_mnItemSalirActionPerformed

    private void btnEntrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProductosActionPerformed

    }//GEN-LAST:event_btnEntrarProductosActionPerformed

    private void btnEntrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarUsuarioActionPerformed

    }//GEN-LAST:event_btnEntrarUsuarioActionPerformed

    private void btnEntrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarProveedorActionPerformed

    }//GEN-LAST:event_btnEntrarProveedorActionPerformed

    private void btnJpReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJpReportesActionPerformed

    }//GEN-LAST:event_btnJpReportesActionPerformed

    private void btnJpMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJpMantenimientoActionPerformed

    }//GEN-LAST:event_btnJpMantenimientoActionPerformed

    private void btnJpVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJpVentaActionPerformed

    }//GEN-LAST:event_btnJpVentaActionPerformed

    private void mnItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCerrarSesionActionPerformed
    
    }//GEN-LAST:event_mnItemCerrarSesionActionPerformed

    private void txtContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaKeyTyped
        //        Character c = evt.getKeyChar();
        //
        //        if (c == '\n') {
            //            if (txtUsuario.getText().equals("admin") && txtContrasenia.getText().equals("12345")) {
                //            JFMenuPrincipal menuP = new JFMenuPrincipal();
                //            this.setVisible(false);
                //            menuP.setVisible(true);
                //        } else {
                //            JOptionPane.showMessageDialog(null, "Ingresaste la clave o contraseña erronea");
                //        }
            //        }
    }//GEN-LAST:event_txtContraseniaKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnNuevoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCliActionPerformed

    }//GEN-LAST:event_btnNuevoCliActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed

    }//GEN-LAST:event_btnBuscarCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnActualizarCli;
    public static javax.swing.JButton btnBuscarCli;
    public static javax.swing.JButton btnEliminarCli;
    private javax.swing.JButton btnEntrarProductos;
    private javax.swing.JButton btnEntrarProveedor;
    private javax.swing.JButton btnEntrarUsuario;
    public static javax.swing.JButton btnExtraer;
    public static javax.swing.JButton btnIngresar;
    public static javax.swing.JButton btnJpCompra;
    public static javax.swing.JButton btnJpConfiguracion;
    public static javax.swing.JButton btnJpMantenimiento;
    public static javax.swing.JButton btnJpReportes;
    public static javax.swing.JButton btnJpVenta;
    public static javax.swing.JButton btnListar;
    public static javax.swing.JButton btnNuevoCli;
    public static javax.swing.JButton btnRegistrarCli;
    public static javax.swing.JComboBox<String> cboGeneroCli;
    public static javax.swing.JComboBox<String> cboGeneroCliM;
    private javax.swing.JLabel icoPass;
    private javax.swing.JLabel icoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel jpBase;
    public static javax.swing.JPanel jpCardCli;
    public static javax.swing.JPanel jpCardMant;
    private javax.swing.JPanel jpClientes;
    public static javax.swing.JPanel jpCompra;
    public static javax.swing.JPanel jpConfiguracion;
    public static javax.swing.JPanel jpConsultaCli;
    public static javax.swing.JPanel jpDatosCli;
    public static javax.swing.JPanel jpIniciarSesion;
    public static javax.swing.JPanel jpMantenimiento;
    public javax.swing.JPanel jpMenu;
    public static javax.swing.JPanel jpModificar;
    private javax.swing.JPanel jpOpcionesCli;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedores;
    public static javax.swing.JPanel jpReportes;
    public static javax.swing.JPanel jpSistemaon;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpUsuarios;
    public static javax.swing.JPanel jpVenta;
    private javax.swing.JLabel lblCantProductos;
    private javax.swing.JLabel lblCantProveedores;
    private javax.swing.JLabel lblCantUsuarios;
    private javax.swing.JLabel lblIcoUser;
    private javax.swing.JLabel lblNombNegocio;
    private javax.swing.JLabel lblNombUser;
    public static javax.swing.JMenuItem mnItemCerrarSesion;
    public static javax.swing.JMenuItem mnItemSalir;
    public static javax.swing.JMenu mnSistema;
    public static javax.swing.JTable tblCliente;
    public static javax.swing.JTextField txtApeMatCli;
    public static javax.swing.JTextField txtApeMatCliM;
    public static javax.swing.JTextField txtApePatCli;
    public static javax.swing.JTextField txtApePatCliM;
    public static javax.swing.JTextField txtCodigoCliM;
    public static javax.swing.JPasswordField txtContrasenia;
    public static javax.swing.JTextField txtDniCli;
    public static javax.swing.JTextField txtDniCliM;
    public static javax.swing.JTextField txtFiltroNombre;
    public static javax.swing.JTextField txtNombreCli;
    public static javax.swing.JTextField txtNombreCliM;
    public static javax.swing.JTextField txtRucCli;
    public static javax.swing.JTextField txtRucCliM;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

        
    
    
}
